### ISSUE TITLE
`echidna` and `medusa` commands from the README not working

### ISSUE THREAD

**Issue by EperezOk** [devdacian/solidity-fuzzing-comparison#1]
I'm trying to run the Medusa and Echidna tests specified in the README, but **none of them are working**.

Foundry tests work as expected.

> I'm using the [Ethereum Security Toolbox](https://github.com/trailofbits/eth-security-toolbox) Docker image from ToB, with `Echidna 2.2.1` and `Medusa 0.1.2`.

## Echidna

For instance, `echidna --config test/02-unstoppable/UnstoppableBasicEchidna.yaml ./ --contract UnstoppableBasicEchidna` outputs:

```
[2024-01-05 02:31:48.78] Compiling ./... Done! (7.752011961s)
echidna: Given contract "UnstoppableBasicEchidna" not found in given file
```

However, I'm able to make echidna work if I specify the path to the `.t.sol` file:

```bash
echidna test/02-unstoppable/UnstoppableBasicEchidna.t.sol --config test/02-unstoppable/UnstoppableBasicEchidna.yaml --contract UnstoppableBasicEchidna
```

## Medusa

On the other hand, when trying to run medusa with `medusa --config test/02-unstoppable/UnstoppableBasicMedusa.json fuzz`, I get:

```
⇾ Reading the configuration file at: test/02-unstoppable/UnstoppableBasicMedusa.json
⇾ Compiling targets with crytic-compile
error Failed to compile target
‣ error while executing crytic-compile:
        OUTPUT:
        INFO:CryticCompile:'forge clean' running (wd: /home/ethsec/solidity-fuzzing-comparison)
        Traceback (most recent call last):
          File "/home/ethsec/.local/bin/crytic-compile", line 8, in <module>
            sys.exit(main())
          File "/home/ethsec/.local/lib/python3.10/site-packages/crytic_compile/__main__.py", line 221, in main
            compilations = compile_all(**vars(args))
          File "/home/ethsec/.local/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 718, in compile_all
            compilations.append(CryticCompile(target, **kwargs))
          File "/home/ethsec/.local/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 207, in __init__
            self._compile(**kwargs)
          File "/home/ethsec/.local/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 629, in _compile
            self._platform.compile(self, **kwargs)
          File "/home/ethsec/.local/lib/python3.10/site-packages/crytic_compile/platform/foundry.py", line 66, in compile
            foundry_config = self.config(str(crytic_compile.working_dir.absolute()))
          File "/home/ethsec/.local/lib/python3.10/site-packages/crytic_compile/platform/foundry.py", line 137, in config
            with open("foundry.toml", "r", encoding="utf-8") as f:
        FileNotFoundError: [Errno 2] No such file or directory: 'foundry.toml'

        ERROR: exit status 1
```

**Comment by devdacian** [comment]
apologies but I'm unable to assist with debugging specific installations or configurations, and I don't use the docker versions myself but manually install everything. Feel free to change the commands to work for you with your particular setup!
